name: "Merge pull requests"

on:
  pull_request:
    types:
      - labeled
      - unlabeled
      - synchronize
      - opened
      - edited
      - ready_for_review
      - reopened
      - unlocked
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed
  status: {}

jobs:
  auto-merge-pr-pre:
    name: Merge
    runs-on: "ubuntu-latest"
    steps:
      - name: Merge pull requests (automerge-action)
        uses: pascalgn/automerge-action@v0.14.2
    
  automerge-pr-release:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "pascalgn/automerge-action@v0.14.2"
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"    
