name: Get logs from Nomad Job
on: [push]
jobs:
  logs:
    name: Nomad Logs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Get logs from Nomad
        uses: younited/nomad-logs-action
        with:
          token: ${{ secrets.YOUR_NOMAD_SECRET }}
          address: ${{ secrets.YOUR_NOMAD_SERVER }}
          job: example-job

# Combine with vault-action
# name: Get logs from Nomad Job
# on: [push]
# jobs:
#   logs:
#     name: Nomad Logs
#     runs-on: ubuntu-latest
#     steps:
#       - name: Checkout
#         uses: actions/checkout@v1
# 
#       - name: Get Nomad token from Hashicorp Vault
#         uses: hashicorp/vault-action@v2.1.2
#         with:
#           url: ${{ secrets.YOUR_VAULT_SERVER }}
#           method: approle
#           roleId: ${{ secrets.VAULT_ROLE_ID }}
#           secretId: ${{ secrets.VAULT_SECRET_ID }}
#           secrets: |
#             nomad/creds/github-action secret_id | NOMAD_TOKEN
# 
#       - name: Get logs from Nomad
#         uses: younited/nomad-logs-action
#         with:
#           token: ${{ env.NOMAD_TOKEN }}
#           address: ${{ secrets.YOUR_NOMAD_SERVER }}
#           job: parameterized-job
#           namespace: my-namespace
#           parameterized: true
