name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.1
      with:
        switches: -avzr --delete
        path: src/
        remote_path: ${{ secrets.GH_RDA_DEPLOY_PATH }}
        remote_host: ${{ secrets.GH_RDA_DEPLOY_HOST }}
        remote_port: ${{ secrets.GH_RDA_DEPLOY_PORT }}
        remote_user: ${{ secrets.GH_RDA_DEPLOY_USER }}
        remote_key: ${{ secrets.GH_RDA_DEPLOY_KEY }}
        remote_key_pass: ${{ secrets.GH_RDA_DEPLOY_KEY_PASS }}
