name: "Skip Duplicate Actions"
uses: fkirc/skip-duplicate-actions@v3.4.1

on:
  push:
    branches: [ origin ]
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ development ]
  schedule:
    - cron: '17 21 * * 1'
  
jobs:
  pre_job:
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          # All of these options are optional, so you can remove them if you are happy with the defaults
          concurrent_skipping: 'never'
          skip_after_successful_duplicate: 'true'
          paths_ignore: '["**/README.md", "**/docs/**"]'
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  main_job:
    needs: pre_job
    if: ${{ needs.pre_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running slow tests..." && sleep 30
      
  final_job: 
    needs: main_job
    if: ${{ needs.main_job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Skip Duplicate Actions
        uses: fkirc/skip-duplicate-actions@v3.4.1
      - run: echo "Running slow tests..." && sleep 40 
   